version: '3.7'

services:

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./sql/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: test
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8090:80"
    volumes:
      - ./pgadmin/config.json:/pgadmin4/servers.json
